# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1054, 771)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(190, 225, 255)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_educational_information = QtWidgets.QLabel(self.centralwidget)
        self.label_educational_information.setGeometry(QtCore.QRect(10, 10, 1031, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_educational_information.setFont(font)
        self.label_educational_information.setAlignment(QtCore.Qt.AlignCenter)
        self.label_educational_information.setObjectName("label_educational_information")
        self.label_institution = QtWidgets.QLabel(self.centralwidget)
        self.label_institution.setGeometry(QtCore.QRect(40, 120, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_institution.setFont(font)
        self.label_institution.setStyleSheet("background-color:rgb(255, 218, 30);\n"
"border-radius:20px;\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-color:rgb(85, 85, 255)")
        self.label_institution.setAlignment(QtCore.Qt.AlignCenter)
        self.label_institution.setObjectName("label_institution")
        self.label_UGCourse = QtWidgets.QLabel(self.centralwidget)
        self.label_UGCourse.setGeometry(QtCore.QRect(40, 220, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_UGCourse.setFont(font)
        self.label_UGCourse.setStyleSheet("background-color:rgb(255, 218, 30);\n"
"border-radius:20px;\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-color:rgb(85, 85, 255)")
        self.label_UGCourse.setAlignment(QtCore.Qt.AlignCenter)
        self.label_UGCourse.setObjectName("label_UGCourse")
        self.label_resume = QtWidgets.QLabel(self.centralwidget)
        self.label_resume.setGeometry(QtCore.QRect(40, 440, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_resume.setFont(font)
        self.label_resume.setStyleSheet("background-color:rgb(255, 218, 30);\n"
"border-radius:20px;\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-color:rgb(85, 85, 255)")
        self.label_resume.setAlignment(QtCore.Qt.AlignCenter)
        self.label_resume.setObjectName("label_resume")
        self.pushButton_submit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_submit.setGeometry(QtCore.QRect(300, 570, 441, 91))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.pushButton_submit.setFont(font)
        self.pushButton_submit.setStyleSheet("background-color:rgb(170, 170, 255);\n"
"border-radius:20px;\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-color:rgb(85, 85, 255);\n"
"\n"
"")
        self.pushButton_submit.setObjectName("pushButton_submit")
        self.comboBox_input_UGCourse = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_input_UGCourse.setGeometry(QtCore.QRect(310, 220, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.comboBox_input_UGCourse.setFont(font)
        self.comboBox_input_UGCourse.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-color:rgb(85, 85, 255)")
        self.comboBox_input_UGCourse.setObjectName("comboBox_input_UGCourse")
        self.comboBox_input_UGCourse.addItem("")
        self.comboBox_input_UGCourse.addItem("")
        self.comboBox_input_UGCourse.addItem("")
        self.comboBox_input_UGCourse.addItem("")
        self.comboBox_input_UGCourse.addItem("")
        self.comboBox_input_UGCourse.addItem("")
        self.label_ug_cgpa = QtWidgets.QLabel(self.centralwidget)
        self.label_ug_cgpa.setGeometry(QtCore.QRect(570, 220, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_ug_cgpa.setFont(font)
        self.label_ug_cgpa.setStyleSheet("background-color:rgb(255, 218, 30);\n"
"border-radius:20px;\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-color:rgb(85, 85, 255)")
        self.label_ug_cgpa.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ug_cgpa.setObjectName("label_ug_cgpa")
        self.label_PGCourse = QtWidgets.QLabel(self.centralwidget)
        self.label_PGCourse.setGeometry(QtCore.QRect(40, 320, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_PGCourse.setFont(font)
        self.label_PGCourse.setStyleSheet("background-color:rgb(255, 218, 30);\n"
"border-radius:20px;\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-color:rgb(85, 85, 255)")
        self.label_PGCourse.setAlignment(QtCore.Qt.AlignCenter)
        self.label_PGCourse.setObjectName("label_PGCourse")
        self.comboBox_input_PGCourse = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_input_PGCourse.setGeometry(QtCore.QRect(310, 320, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.comboBox_input_PGCourse.setFont(font)
        self.comboBox_input_PGCourse.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-color:rgb(85, 85, 255)")
        self.comboBox_input_PGCourse.setObjectName("comboBox_input_PGCourse")
        self.comboBox_input_PGCourse.addItem("")
        self.comboBox_input_PGCourse.addItem("")
        self.comboBox_input_PGCourse.addItem("")
        self.comboBox_input_PGCourse.addItem("")
        self.comboBox_input_PGCourse.addItem("")
        self.comboBox_input_PGCourse.addItem("")
        self.label_pg_cgpa = QtWidgets.QLabel(self.centralwidget)
        self.label_pg_cgpa.setGeometry(QtCore.QRect(570, 320, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_pg_cgpa.setFont(font)
        self.label_pg_cgpa.setStyleSheet("background-color:rgb(255, 218, 30);\n"
"border-radius:20px;\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-color:rgb(85, 85, 255)")
        self.label_pg_cgpa.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pg_cgpa.setObjectName("label_pg_cgpa")
        self.lineEdit_input_institution = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_input_institution.setGeometry(QtCore.QRect(310, 120, 691, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_input_institution.setFont(font)
        self.lineEdit_input_institution.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"padding:5px;\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-color:rgb(85, 85, 255)")
        self.lineEdit_input_institution.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_input_institution.setObjectName("lineEdit_input_institution")
        self.lineEdit_input_resume = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_input_resume.setGeometry(QtCore.QRect(310, 440, 691, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_input_resume.setFont(font)
        self.lineEdit_input_resume.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"padding:5px;\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-color:rgb(85, 85, 255)")
        self.lineEdit_input_resume.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_input_resume.setObjectName("lineEdit_input_resume")
        self.lineEdit_input_pg_cgpa = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_input_pg_cgpa.setGeometry(QtCore.QRect(760, 320, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_input_pg_cgpa.setFont(font)
        self.lineEdit_input_pg_cgpa.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-color:rgb(85, 85, 255)")
        self.lineEdit_input_pg_cgpa.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_input_pg_cgpa.setObjectName("lineEdit_input_pg_cgpa")
        self.lineEdit_input_ug_cgpa = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_input_ug_cgpa.setGeometry(QtCore.QRect(760, 220, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_input_ug_cgpa.setFont(font)
        self.lineEdit_input_ug_cgpa.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-color:rgb(85, 85, 255)")
        self.lineEdit_input_ug_cgpa.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_input_ug_cgpa.setObjectName("lineEdit_input_ug_cgpa")
        self.pushButton_folder = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_folder.setGeometry(QtCore.QRect(910, 440, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton_folder.setFont(font)
        self.pushButton_folder.setStyleSheet("padding:5px;\n"
"border:2px solid rgba(0,0,0,0);\n"
"border-color:rgb(85, 85, 255)")
        self.pushButton_folder.setObjectName("pushButton_folder")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1054, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_educational_information.setText(_translate("MainWindow", "Educational Information 🎓 "))
        self.label_institution.setText(_translate("MainWindow", "Your institution"))
        self.label_UGCourse.setText(_translate("MainWindow", "UG Course"))
        self.label_resume.setText(_translate("MainWindow", "Your resume"))
        self.pushButton_submit.setText(_translate("MainWindow", "Submit"))
        self.comboBox_input_UGCourse.setItemText(0, _translate("MainWindow", "Select"))
        self.comboBox_input_UGCourse.setItemText(1, _translate("MainWindow", "B .A"))
        self.comboBox_input_UGCourse.setItemText(2, _translate("MainWindow", "B .Com"))
        self.comboBox_input_UGCourse.setItemText(3, _translate("MainWindow", "B .Tech"))
        self.comboBox_input_UGCourse.setItemText(4, _translate("MainWindow", "BSc"))
        self.comboBox_input_UGCourse.setItemText(5, _translate("MainWindow", "B .Arch"))
        self.label_ug_cgpa.setText(_translate("MainWindow", "CGPA"))
        self.label_PGCourse.setText(_translate("MainWindow", "PG Course"))
        self.comboBox_input_PGCourse.setItemText(0, _translate("MainWindow", "Select"))
        self.comboBox_input_PGCourse.setItemText(1, _translate("MainWindow", "M .A"))
        self.comboBox_input_PGCourse.setItemText(2, _translate("MainWindow", "M .Com"))
        self.comboBox_input_PGCourse.setItemText(3, _translate("MainWindow", "M .Tech"))
        self.comboBox_input_PGCourse.setItemText(4, _translate("MainWindow", "MSc"))
        self.comboBox_input_PGCourse.setItemText(5, _translate("MainWindow", "MS"))
        self.label_pg_cgpa.setText(_translate("MainWindow", "CGPA"))
        self.lineEdit_input_institution.setPlaceholderText(_translate("MainWindow", "Type your institution name"))
        self.lineEdit_input_resume.setPlaceholderText(_translate("MainWindow", "Upload your resume from this device"))
        self.pushButton_folder.setText(_translate("MainWindow", "📂"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
